import { Product } from '../../types';

const sizes = ['P', 'M', 'G', 'GG', 'XGG'] as const;

const details = {
  fabric: 'Tecido esportivo respirável',
  shield: 'Acabamento premium',
  origin: 'Importada',
};

const baseImage = '/stores/manto-prime/products/';

export const mantoPrimeProducts: Product[] = [
  {
    id: 'manto-prime-palmeiras-home',
    name: 'Palmeiras Home',
    team: 'Palmeiras',
    league: 'Brasileirão Série A',
    category: ['brasileirao'],
    price: 149.90,
    image: `${baseImage}palmeiras-home-frente.jpeg`,
    images: [
      `${baseImage}palmeiras-home-frente.jpeg`,
      `${baseImage}palmeiras-home-costa.jpeg`,
      `${baseImage}palmeiras-home02.jpeg`,
      `${baseImage}palmeiras-home03.jpeg`,
    ],
    sizes: [...sizes],
    isFeatured: true,
    isBestSeller: true,
    badge: 'Destaque',
    description: 'Camisa Palmeiras Home disponível na Manto Prime.',
    version: 'Torcedor',
    year: '2025/26',
    details,
  },
  {
    id: 'manto-prime-palmeiras-away',
    name: 'Palmeiras Away',
    team: 'Palmeiras',
    league: 'Brasileirão Série A',
    category: ['brasileirao'],
    price: 149.90,
    image: `${baseImage}palmeiras-away-frente.jpeg`,
    images: [
      `${baseImage}palmeiras-away-frente.jpeg`,
      `${baseImage}palmeiras-away-costa.jpeg`,
      `${baseImage}palmeiras-away02.jpeg`,
      `${baseImage}palmeiras-away03.jpeg`,
    ],
    sizes: [...sizes],
    description: 'Camisa Palmeiras Away disponível na Manto Prime.',
    version: 'Torcedor',
    year: '2025/26',
    details,
  },
  {
    id: 'manto-prime-corinthians-home',
    name: 'Corinthians Home',
    team: 'Corinthians',
    league: 'Brasileirão Série A',
    category: ['brasileirao'],
    price: 179.90,
    image: `${baseImage}corinthians-home-frente .jpeg`,
    images: [
      `${baseImage}corinthians-home-frente .jpeg`,
    ],
    sizes: [...sizes],
    isFeatured: true,
    isBestSeller: true,
    badge: 'Destaque',
    description: 'Camisa Corinthians Home disponível na Manto Prime.',
    version: 'Torcedor',
    year: '2025/26',
    details,
  },
  {
    id: 'manto-prime-corinthians-away',
    name: 'Corinthians Away',
    team: 'Corinthians',
    league: 'Brasileirão Série A',
    category: ['brasileirao'],
    price: 179.90,
    image: `${baseImage}corinthians-away-frente.jpeg`,
    images: [
      `${baseImage}corinthians-away-frente.jpeg`,
    ],
    sizes: [...sizes],
    description: 'Camisa Corinthians Away disponível na Manto Prime.',
    version: 'Torcedor',
    year: '2025/26',
    details,
  },
  {
    id: 'manto-prime-flamengo-home',
    name: 'Flamengo Home',
    team: 'Flamengo',
    league: 'Brasileirão Série A',
    category: ['brasileirao'],
    price: 179.90,
    image: `${baseImage}flamengo-home-jogador.jpeg`,
    images: [
      `${baseImage}flamengo-home-jogador.jpeg`,
      `${baseImage}flamengo-home-jogador-costa.jpeg`,
    ],
    sizes: [...sizes],
    isFeatured: true,
    isBestSeller: true,
    badge: 'Destaque',
    description: 'Camisa Flamengo Home disponível na Manto Prime.',
    version: 'Torcedor',
    year: '2025/26',
    details,
  },
  {
    id: 'manto-prime-flamengo-away',
    name: 'Flamengo Away',
    team: 'Flamengo',
    league: 'Brasileirão Série A',
    category: ['brasileirao'],
    price: 179.90,
    image: `${baseImage}flamengo-away-frente.jpeg`,
    images: [
      `${baseImage}flamengo-away-frente.jpeg`,
      `${baseImage}flamengo-away-costa.jpeg`,
    ],
    sizes: [...sizes],
    description: 'Camisa Flamengo Away disponível na Manto Prime.',
    version: 'Torcedor',
    year: '2025/26',
    details,
  },
];
